import Head from 'next/head';

{/*import { Inter } from '@next/font/google';*/}

import LayoutLandingPage from '@/layouts/LayoutLandingpage';
import SectionSlider from '@/components/landingpage/SectionSlider';
import SectionCard from '@/components/landingpage/SectionCard';
import SectionAskCard from '@/components/landingpage/SectionAskCard';
import SectionAskCardV2 from '@/components/landingpage/SectionAskCardV2';
import SectionMarmed from '@/components/landingpage/SectionMarmed';
import Footer from '@/components/landingpage/Footer';
import SectionPartner from '@/components/landingpage/SectionPartner';
import SectionAskCardChat from '@/components/landingpage/SectionAskCardChat';
import SectionPrices from '@/components/landingpage/SectionPrices';

{/*const inter = Inter({ subsets: ['latin'] });*/}

export default function Home() {
  return (
    <>
      <Head>
        <title>Cartão Mais Você</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LayoutLandingPage>
          <SectionSlider />
          <SectionCard />
          <SectionAskCard />
          <SectionMarmed />
          <SectionAskCardV2 />
          <SectionPartner />
          <SectionAskCardChat />
          {/*
  */}
        </LayoutLandingPage>
      </main>
    </>
  )
}
