import Head from 'next/head';

import LayoutLandingPage from '@/layouts/LayoutLandingpage';
import styles from './forgotpassword.module.scss';
import bannerlogin from '../../../public/images/logotipo2.png';

import Image from 'next/image';
import Link from 'next/link';
import { AuthContext } from '@/contexts/AuthContext';
import { useContext, useEffect } from 'react';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { api } from "../../services/api";


export default function ForgotPassword() {

  const router = useRouter();

  const [emailValue, setEmailValue] = useState('');

  const handleSubmitSendPassword = async (e) => {
    e.preventDefault();
    
    const email = {
      email: emailValue
    }

    console.log(email);

    try {
      const response = await api.post(`/api/usuarios/sendmaillink`, email)
      if (response.status === 200) {
        alert('Email enviado com sucesso. Verifique sua caixa de entrada para redefinir sua senha.');
        router.push('/login');
      } else {
        alert('Erro ao enviar email.');
      }
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <>
      <Head>
        <title>Cartão Mais Você</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LayoutLandingPage>
          <div className={styles.login}>
            <div className={styles.container}>
              <div className={styles.loginleft}>
                <form className={styles.loginleft} onSubmit={handleSubmitSendPassword}>
                  <span className={styles.logintitle}><span className={styles.logintitlename}>Envie o email para redefinir senha.</span></span>
                  <input
                    className={styles.logininput}
                    id="email"
                    type="text"
                    name="email"
                    placeholder="exemplo@email.com"
                    maxLength="70"
                    onChange={e => setEmailValue(e.target.value)}
                    required
                  />
                  <button
                    className={styles.loginbtn}
                    type="submit">
                    Enviar
                  </button>
                </form>
              </div>
              <div>
                <div className={styles.loginright}>
                  <Image src={bannerlogin} className={styles.loginbanner} alt='banner2' />
                </div>
                <span className={styles.titleadmin}>Administrativo</span>
              </div>
            </div>
          </div>
        </LayoutLandingPage>
      </main>
    </>
  )
}
